# ----------------------------------------------------------------------
# Transformations
# ----------------------------------------------------------------------
# Augmentations for `train Dataset`
augmentation:
  train:
    # Specify augments here
    # class_name : name of the albumentation function
    # p : probability
    augs:
      - class_name: albumentations.Flip
        params:
          p: 0.6

      - class_name: albumentations.ShiftScaleRotate
        params:
          p: 0.6

      - class_name: albumentations.HorizontalFlip
        params:
          p: 0.6

      - class_name: albumentations.CLAHE
        params:
          p: 0.6

      - class_name: albumentations.ToGray
        params:
          p: 0.21

      - class_name: albumentations.RandomBrightnessContrast
        params:
          p: 0.6

      - class_name: albumentations.ToFloat
        params:
          max_value: 255.0
          always_apply: True

      - class_name: albumentations.pytorch.transforms.ToTensorV2
        params:
          always_apply: True

    # Bbox_parameters
    bbox_params:
      format: pascal_voc
      label_fields:
        - class_labels

  # Augmentations for `valid dataset`
  valid:
    # Specify augments here
    # class_name : name of the albumentation function
    # p : probability
    augs:
      - class_name: albumentations.ToFloat
        params:
          max_value: 255.0
          always_apply: True

      - class_name: albumentations.pytorch.transforms.ToTensorV2
        params:
          always_apply: True

    # Bbox_parameters
    bbox_params:
      # Bbox _params
      format: pascal_voc
      label_fields:
        - class_labels
