# ----------------------------------------------------------------------
# Transformations
# ----------------------------------------------------------------------
# Augmentations for `train Dataset`
augmentation:
  train:
    augs:
      - class_name: albumentations.HorizontalFlip
        params:
          p: 0.6

      - class_name: albumentations.CLAHE
        params:
          p: 0.6

      - class_name: albumentations.ToGray
        params:
          p: 0.21

      - class_name: albumentations.RandomBrightnessContrast
        params:
          p: 0.6

      - class_name: albumentations.RandomSizedBBoxSafeCrop
        params:
          width: 448
          height: 336
          erosion_rate: 0.2
          p: 0.2

      - class_name: albumentations.ToFloat
        params:
          max_value: 255.0
          always_apply: True

      - class_name: albumentations.pytorch.transforms.ToTensorV2
        params:
          always_apply: True

    bbox_params:
      format: pascal_voc
      label_fields:
        - class_labels

  # Augmentations for `valid dataset`
  valid:
    augs:
      - class_name: albumentations.ToFloat
        params:
          max_value: 255.0
          always_apply: True

      - class_name: albumentations.pytorch.transforms.ToTensorV2
        params:
          always_apply: True

    bbox_params:
      format: pascal_voc
      label_fields:
        - class_labels
